### ISSUE TITLE
missing entry field results in 500 error

### ISSUE THREAD

**Issue by FND** [innoq/iBlog#110]
```
$ curl -v -u fnd:... --data-urlencode "entry%5Btitle%5D=test" \
        --data-urlencode "entry%5Bprogress%5D=lipsum" \
        https://internal.innoq.com/blogging/blogs/37/entries
...
< HTTP/1.1 500 Internal Server Error
...
<h1>We're sorry, but something went wrong.</h1>
```

The application currently can't handle any of the "progress", "plans" or "problems" fields missing.

Educated guess: The Markdown processing can't deal with `nil` values.

PS: Are whitespace-only strings currently treated as empty strings? (They should be.)

**Comment by mjansing** [comment]
Already fixed.
