### ISSUE TITLE
einige Blogs produzieren HTTP 500 - gewollt?

### ISSUE THREAD

**Issue by phaus** [innoq/iBlog#122]
Beim Aufruf von ein paar URLs erhält man einen HTTP Status 500. 

https://example.org/blogs/10	500
https://example.org/blogs/11	500
https://example.org/blogs/12	500
https://example.org/blogs/13	500
https://example.org/blogs/14	500
https://example.org/blogs/15	500
https://example.org/blogs/16	500
https://example.org/blogs/17	500
https://example.org/blogs/18	500
https://example.org/blogs/19	500
https://example.org/blogs/20	500
https://example.org/blogs/21	500
https://example.org/blogs/22	500
https://example.org/blogs/24	500
https://example.org/blogs/25	500
https://example.org/blogs/26	500
https://example.org/blogs/27	500
https://example.org/blogs/28	500
https://example.org/blogs/29	500
https://example.org/blogs/3	  500
https://example.org/blogs/30	500
https://example.org/blogs/31	500
https://example.org/blogs/32	500
https://example.org/blogs/33	500
https://example.org/blogs/34	500
https://example.org/blogs/35	500
https://example.org/blogs/37	500
https://example.org/blogs/38	500
https://example.org/blogs/39	500
https://example.org/blogs/4	  500
https://example.org/blogs/40	500
https://example.org/blogs/41	500
https://example.org/blogs/42	500
https://example.org/blogs/43	500
https://example.org/blogs/44	500
https://example.org/blogs/45	500
https://example.org/blogs/46	500
https://example.org/blogs/47	500
https://example.org/blogs/48	500
https://example.org/blogs/49	500
https://example.org/blogs/50	500
https://example.org/blogs/51	500
https://example.org/blogs/52	500
https://example.org/blogs/53	500
https://example.org/blogs/55	500
https://example.org/blogs/56	500
https://example.org/blogs/57	500
https://example.org/blogs/58	500
https://example.org/blogs/59	500
https://example.org/blogs/6	500
https://example.org/blogs/60	500
https://example.org/blogs/61	500
https://example.org/blogs/62	500
https://example.org/blogs/63	500
https://example.org/blogs/7	500
https://example.org/blogs/8	500
https://example.org/blogs/9	500

Ist das ein Problem oder bekannt/gewollt?

**Comment by phaus** [comment]
ich denke da müsste man mal in die Logs gucken. Vermutlich ist der Fehler bei allen identisch. @offlinehoster besteht die Chance das mal n Snippet vom Request zu bekommen?

**Comment by offlinehoster** [comment]
Aber die URLS lauten doch 

https://intern.innoq.com/blogging/blogs/10/entries
und nicht 
https://intern.innoq.com/blogging/blogs/10/

**Comment by mjansing** [comment]
@phaus Keep in Mind that this is a public repository.

**Comment by mjansing** [comment]
I added a redirection to this route. 

@phaus: Maybe `/status` might be interesting for you.

**Comment by phaus** [comment]
naja... ein redirect behept aber nicht das problem oder? /status zeigt mir an, wie /status gerendert wird? Zumindest sehe ich da nix von nem Fehler oder nem Redirect :-)
