### ISSUE TITLE
Tags sollten ohne Komma in die Datenbank

### ISSUE THREAD

**Issue by aknrdureegaesr** [innoq/iBlog#123]
Der Fix von #116 führt dazu, dass Tags mit anschließendem Komma in der Datenbank landen.

Am SQL-Prompt der Produktionsdatenbank:

    mysql> select name, count(*) anz from tags t
        group by name having 40 < anz order by anz desc;
    +-------------------------------+-----+
    | name                          | anz |
    +-------------------------------+-----+
    | Rating                        | 167 |
    | Retail                        | 124 |
    | global                        | 111 |
    | Projekt_OptimierungCorporates |  97 |
    | Wartung                       |  85 |
    | rollout                       |  82 |
    | CF-Tool                       |  77 |
    | CF-Tool,                      |  61 |
    | Ships                         |  42 |
    | 2.0                           |  42 |
    +-------------------------------+-----+
    12 rows in set (0.00 sec)

Für den Fix:
* derzeitige Probleme migrieren
* keine neuen Kommas in die Datenbank.

**Comment by mjansing** [comment]
Fixed with 2d41844d531948a53bff4225f32e0f0a17239679.
