### ISSUE TITLE
Textareas for adding content are too small by default.

### ISSUE THREAD

**Issue by aknrdureegaesr** [innoq/iBlog#193]
Issue #2 is back:

I want to enter an entry or status. My browser windows is 1500 something pixel wide. Of this screen space, the main GUI element I'm interacting with, the text field I use to enter my content, gets a mere 800 something pixel. A lot of space to the left and to the right of that text area remains unused. I want to have that space for added convenience in typing.

If the gods of good taste have mercy on me, I would love the headlines (like "Blog", "Titel" and so on) to _precede_ the  text area they refer to, instead of sticking out to the left, wasting even more width.

Workaround: I can presently enlarge the text area manually, using my browser's UI.  I would prefer not having to do that after each single preview when authoring a longish text.

**Comment by mjansing** [comment]
Fixed via 2f53e21
