### ISSUE TITLE
Knopf zum (normalerweise) nicht-drücken ist größer.

### ISSUE THREAD

**Issue by aknrdureegaesr** [innoq/iBlog#72]
Der Knopf, den man (normalerweise) _nicht_ drücken soll, jedenfalls nicht ohne gut drüber nachzudenken, genau der ist _dicker_ als die anderen.

[Schirmschuss](https://github.com/aknrdureegaesr/iBlog/blob/pictures/DangerousAttraction.png)

Ich würde es eher andersrum machen, ihn kleiner machen oder höchstens genau so groß.

Gibt es dafür eine sinnige Erklärung? Habe ich einen Bug gefunden? Wie soll ich darüber denken?

**Comment by martinei** [comment]
Screenshot leider nicht mehr sichtbar. Der Text verrät nix über die Intention.
