### ISSUE TITLE
Produktionslog zu detailliert, sollte nur Probleme/Warnungen melden.

### ISSUE THREAD

**Issue by aknrdureegaesr** [innoq/iBlog#82]
Das Produktionslog funktionierte (vermutlich seit 14. August) nicht, da die zu schreibende Log-Datei dem User `www-data` gehörte, die Anwendung aber unter dem User `iblog` läuft. Dieses Permissionproblem habe ich eben gefixt. Aber jetzt stellt sich heraus, dass das Produktionslog noch genau so geschwätzig eingestellt ist wie das Log für Entwicklung.

**Comment by mjansing** [comment]
Fixed in internal engine mounting app.
