### ISSUE TITLE
border-radius mixin is deprecated

### ISSUE THREAD

**Issue by aknrdureegaesr** [innoq/iBlog#83]
Beim Deployment von iBlog eben:

    WARNING: border-radius mixin is deprecated and will be removed in the next major version release.
             on line 3 of /home/iblog/iblog/vendor/bundle/ruby/1.8/gems/bourbon-2.1.1/app/assets/stylesheets/css3/_border-radius.scss
             from line 46 of /home/iblog/iblog/app/assets/stylesheets/iblog.css.scss
             from line 8 of /home/iblog/iblog/app/assets/stylesheets/application.css.scss

Sollten wir gelegentlich ausbauen.

Ist das ein "Upstream" - Problem?

**Comment by mjansing** [comment]
Fixed with 98841048823d4b0a2104bbe3f860c0b1f47b43af

**Comment by mrreynolds** [comment]
@mjansing hardcoding vendor prefixes is something we shouldn't do. What about using [autoprefixer](https://github.com/ai/autoprefixer-rails) for this?
